"""Point-in-time OHLCV signal construction for the confirmed 20-slot experiment.

Inputs are already-admitted raw bars, event factors and universe membership.
This module never infers missing bars, event coverage or trading status.
"""

from __future__ import annotations

from collections import defaultdict
from decimal import Decimal

import pandas as pd


def _decimal(value: object) -> Decimal:
    result = Decimal(str(value))
    if not result.is_finite():
        raise ValueError("NONFINITE_SIGNAL_INPUT")
    return result


def _date(value: object) -> pd.Timestamp:
    result = pd.Timestamp(value)
    if pd.isna(result) or result.tzinfo is not None or result != result.normalize():
        raise ValueError("INVALID_SIGNAL_DATE")
    if not pd.Timestamp("2014-01-01") <= result < pd.Timestamp("2024-01-01"):
        raise ValueError("SIGNAL_DATE_OUTSIDE_LOCKED_WINDOW")
    return result


def build_ohlcv20_signals(
    prices: pd.DataFrame,
    factors: pd.DataFrame,
    calendars: dict[str, list[object]],
    *,
    corporate_coverage_certified: bool,
) -> dict[str, pd.DataFrame]:
    """Return signals and explicit skips using facts known at each close.

    A factor on effective date E multiplies observations before E. The low
    comparison uses the t-1 basis; daily return and volume use the t basis.
    This distinguishes an ex-date event on the signal day from a price rise.
    ``corporate_coverage_certified`` is a caller-side complete-event assertion,
    never generated by this function.
    """
    if corporate_coverage_certified is not True:
        raise ValueError("CORPORATE_EVENT_COVERAGE_NOT_CERTIFIED")
    required = {
        "date",
        "code",
        "market",
        "open",
        "high",
        "low",
        "close",
        "volume",
        "turnover",
        "eligible",
        "can_signal",
    }
    if not required <= set(prices.columns):
        raise ValueError(
            "MISSING_SIGNAL_BAR_FIELDS:"
            + ",".join(sorted(required - set(prices.columns)))
        )
    factor_required = {
        "code",
        "effective_date",
        "price_factor",
        "volume_factor",
        "known_at",
        "known_before_close",
        "price_admitted",
        "volume_admitted",
    }
    if not factor_required <= set(factors.columns):
        raise ValueError(
            "MISSING_FACTOR_FIELDS:"
            + ",".join(sorted(factor_required - set(factors.columns)))
        )
    days_by_market: dict[str, list[pd.Timestamp]] = {}
    for market in ("KOSPI", "KOSDAQ"):
        days = [_date(value) for value in calendars.get(market, [])]
        if not days or days != sorted(set(days)):
            raise ValueError("INVALID_MARKET_CALENDAR:" + market)
        days_by_market[market] = days
    events: dict[str, list[dict]] = defaultdict(list)
    seen_events: set[tuple[str, pd.Timestamp]] = set()
    for row in factors.to_dict("records"):
        code, effective, known = (
            str(row["code"]),
            _date(row["effective_date"]),
            _date(row["known_at"]),
        )
        key = code, effective
        if key in seen_events:
            raise ValueError("DUPLICATE_FACTOR_DATE")
        seen_events.add(key)
        if (
            type(row["price_admitted"]) is not bool
            or type(row["volume_admitted"]) is not bool
            or type(row["known_before_close"]) is not bool
        ):
            raise ValueError("EXPLICIT_FACTOR_ADMISSION_REQUIRED")
        price_factor, volume_factor = (
            _decimal(row["price_factor"]),
            _decimal(row["volume_factor"]),
        )
        if price_factor <= 0 or volume_factor <= 0:
            raise ValueError("INVALID_EVENT_FACTOR")
        events[code].append(
            dict(
                date=effective,
                known=known,
                known_before_close=row["known_before_close"],
                price=price_factor,
                volume=volume_factor,
                admitted=row["price_admitted"] and row["volume_admitted"],
            )
        )
    for rows in events.values():
        rows.sort(key=lambda row: row["date"])

    by_code: dict[str, list[dict]] = defaultdict(list)
    seen_bars: set[tuple[str, pd.Timestamp]] = set()
    for row in prices.to_dict("records"):
        code, date, market = str(row["code"]), _date(row["date"]), str(row["market"])
        if market not in days_by_market or date not in days_by_market[market]:
            raise ValueError("BAR_OFF_MARKET_CALENDAR")
        key = code, date
        if key in seen_bars:
            raise ValueError("DUPLICATE_SIGNAL_BAR")
        seen_bars.add(key)
        if type(row["eligible"]) is not bool or type(row["can_signal"]) is not bool:
            raise ValueError("EXPLICIT_SIGNAL_FLAGS_REQUIRED")
        for field in ("open", "high", "low", "close", "volume", "turnover"):
            row[field] = _decimal(row[field])
        row["date"] = date
        if (
            row["volume"] < 0
            or row["turnover"] < 0
            or row["low"] <= 0
            or row["low"] > min(row["open"], row["close"])
            or row["high"] < max(row["open"], row["close"])
        ):
            raise ValueError("INVALID_SIGNAL_OHLCV")
        by_code[code].append(row)
    signals, skipped = [], []
    calendar_positions = {
        m: {day: i for i, day in enumerate(days)} for m, days in days_by_market.items()
    }
    for code, bars in sorted(by_code.items()):
        bars.sort(key=lambda row: row["date"])
        event_rows = events.get(code, [])
        for index in range(60, len(bars)):
            row, previous = bars[index], bars[index - 1]
            date, market = row["date"], str(row["market"])
            if not row["eligible"] or not row["can_signal"]:
                continue
            calendar = days_by_market[market]
            pos = calendar_positions[market][date]
            window = bars[index - 60 : index]
            if pos < 60 or [r["date"] for r in window] != calendar[pos - 60 : pos]:
                skipped.append(
                    dict(date=date, code=code, reason="INCOMPLETE_60_SESSION_WINDOW")
                )
                continue
            if any(not r["can_signal"] for r in window):
                skipped.append(
                    dict(date=date, code=code, reason="UNVERIFIED_WINDOW_BAR")
                )
                continue
            recent = bars[index - 19 : index + 1]
            if (
                len(recent) != 20
                or sum(r["turnover"] for r in recent) <= 0
                or row["turnover"] <= 0
                or previous["volume"] <= 0
                or row["volume"] <= 0
            ):
                skipped.append(
                    dict(date=date, code=code, reason="INCOMPLETE_LIQUIDITY_INPUT")
                )
                continue
            relevant = [
                event
                for event in event_rows
                if window[0]["date"] < event["date"] <= date
            ]
            if any(
                not event["admitted"]
                or event["known"] > date
                or (event["known"] == date and not event["known_before_close"])
                for event in relevant
            ):
                skipped.append(
                    dict(date=date, code=code, reason="UNADMITTED_OR_FUTURE_FACTOR")
                )
                continue
            if any(
                event["date"] <= previous["date"]
                and (
                    event["known"] > previous["date"]
                    or (
                        event["known"] == previous["date"]
                        and not event["known_before_close"]
                    )
                )
                for event in relevant
            ):
                skipped.append(
                    dict(date=date, code=code, reason="FACTOR_KNOWN_AFTER_PRIOR_BASIS")
                )
                continue

            def adjusted(
                value: Decimal,
                observation: pd.Timestamp,
                basis: pd.Timestamp,
                field: str,
            ) -> Decimal:
                for event in relevant:
                    if observation < event["date"] <= basis:
                        value *= event[field]
                return value

            prior_basis = previous["date"]
            previous_close_low_basis = previous["close"]
            low60 = min(
                adjusted(r["low"], r["date"], prior_basis, "price") for r in window
            )
            if previous_close_low_basis > low60 * Decimal("1.2"):
                continue
            prior_close_today_basis = adjusted(
                previous["close"], prior_basis, date, "price"
            )
            previous_volume_today_basis = adjusted(
                previous["volume"], prior_basis, date, "volume"
            )
            if row["volume"] < previous_volume_today_basis * 2:
                continue
            threshold = Decimal("0.1") if market == "KOSPI" else Decimal("0.15")
            if row["close"] < prior_close_today_basis * (1 + threshold):
                continue
            signals.append(
                dict(
                    signal_date=date,
                    code=code,
                    market=market,
                    turnover=row["turnover"],
                    mean_turnover20=sum(r["turnover"] for r in recent) / 20,
                    limit_price=row["close"],
                    eligible=True,
                )
            )
    return {"signals": pd.DataFrame(signals), "skipped": pd.DataFrame(skipped)}
